#ifndef SCENE_H
#define SCENE_H

#include "core/config.h"
#include <vector>

struct Scene {
    const char* name;
    FluidConfig fluid;
    float camYaw;
    float camPitch;
    float camDist;
    float pointSize;
};

inline const std::vector<Scene>& getScenes()
{
    static const std::vector<Scene> scenes = {

		// 0 — Default Test
        {
            "Default Test",
            {
                /* dt */                1.0f / 60.0f,
                /* gravity */           { 0.0f, -3.81f, 0.0f },
                /* h */                 0.14f,
                /* rho0 */              1000.0f,
                /* solverIterations */   3,
                /* substepIterations */  2,
                /* eps */               0.0001f,
                /* particleCount */     1 << 15,
                /* spawnMin */          { 2.f, 0.2f, 2.f },
                /* spawnMax */          { 5.f, 5.f, 5.f },
                /* spawnRandom */       false,
                /* spacing */           0.1f,
                /* initialVelocity */   { 0.0f, 0.0f, 0.0f },
                /* boundsMin */         { 0.0f, 0.0f, 0.0f },
                /* boundsMax */         { 6.0f, 6.0f, 6.0f },
                /* boundDamping */      0.5f,
                /* hashSize */          1 << 17,
                /* enableSCorr */       true,
                /* kCorr */             0.001f,
                /* nCorr */             4.0f,
                /* deltaQ */            0.3f,
                /* cohesionStrength */  0.001f,
                /* enableViscosity */   true,
                /* viscosity */         0.1f,
                /* interactionRadius */ 1.5f,
                /* interactionStrength */ 25.0f,
                /* enableVorticity */   true,
                /* vorticityEpsilon */  0.05f,
            },
            /* camYaw */   0.6f,
            /* camPitch */ 0.5f,
            /* camDist */  12.0f,
            /* pointSize */ 8.0f,
        },

        // 1 — Dam Break: tall column on left side collapses across the floor
        {
            "Dam Break",
            {
                /* dt */                1.0f / 60.0f,
                /* gravity */           { 0.0f, -9.81f, 0.0f },
                /* h */                 0.15f,
                /* rho0 */              1200.0f,
                /* solverIterations */   4,
                /* substepIterations */  3,
                /* eps */               0.0001f,
                /* particleCount */     1 << 16,
                /* spawnMin */          { 0.1f, 0.1f, 0.1f },
                /* spawnMax */          { 2.5f, 5.8f, 5.8f },
                /* spawnRandom */       false,
                /* spacing */           0.1f,
                /* initialVelocity */   { 0.0f, 0.0f, 0.0f },
                /* boundsMin */         { 0.0f, 0.0f, 0.0f },
                /* boundsMax */         { 8.0f, 6.0f, 6.0f },
                /* boundDamping */      0.4f,
                /* hashSize */          1 << 18,
                /* enableSCorr */       true,
                /* kCorr */             0.001f,
                /* nCorr */             4.0f,
                /* deltaQ */            0.3f,
                /* cohesionStrength */  0.001f,
                /* enableViscosity */   true,
                /* viscosity */         0.1f,
                /* interactionRadius */ 1.5f,
                /* interactionStrength */ 25.0f,
                /* enableVorticity */   true,
                /* vorticityEpsilon */  0.05f,
            },
            /* camYaw */   0.45f,
            /* camPitch */ 0.4f,
            /* camDist */  15.0f,
            /* pointSize */ 7.0f,
        },

        // 2 — Dripping Faucet
        {
            "Dripping Faucet",
            {
                /* dt */                1.0f / 60.0f,
                /* gravity */           { 0.0f, -4.0f, 0.0f },
                /* h */                 0.15f,
                /* rho0 */              1200.0f,
                /* solverIterations */   4,
                /* substepIterations */  3,
                /* eps */               0.0001f,
                /* particleCount */     1 << 14,
                /* spawnMin */          { 1.4f, 4.1f, 1.3f },
                /* spawnMax */          { 2.0f, 4.5f, 2.0f },
                /* spawnRandom */       false,
                /* spacing */           0.02f,
                /* initialVelocity */   { 0.0f, 0.0f, 0.0f },
                /* boundsMin */         { 0.0f, 0.0f, 0.0f },
                /* boundsMax */         { 3.0f, 5.0f, 3.0f },
                /* boundDamping */      0.5f,
                /* hashSize */          1 << 16,
                /* enableSCorr */       true,
                /* kCorr */             0.001f,
                /* nCorr */             4.0f,
                /* deltaQ */            0.3f,
                /* cohesionStrength */  0.001f,
                /* enableViscosity */   true,
                /* viscosity */         0.1f,
                /* interactionRadius */ 1.5f,
                /* interactionStrength */ 25.0f,
                /* enableVorticity */   true,
                /* vorticityEpsilon */  0.05f,
            },
            /* camYaw */   0.6f,
            /* camPitch */ 0.5f,
            /* camDist */  10.0f,
            /* pointSize */ 8.0f,
        },

        // 3 — Large Tank
        {
            "Large Tank",
            {
                /* dt */                1.0f / 60.0f,
                /* gravity */           { 0.0f, -5.0f, 0.0f },
                /* h */                 0.15f,
                /* rho0 */              1000.0f,
                /* solverIterations */   4,
                /* substepIterations */  3,
                /* eps */               0.0001f,
                /* particleCount */     1 << 17,
                /* spawnMin */          { 0.2f, 0.2f, 0.2f },
                /* spawnMax */          { 9.8f, 3.0f, 9.8f },
                /* spawnRandom */       false,
                /* spacing */           0.12f,
                /* initialVelocity */   { 0.0f, 0.0f, 0.0f },
                /* boundsMin */         { 0.0f, 0.0f, 0.0f },
                /* boundsMax */         { 10.0f, 6.0f, 10.0f },
                /* boundDamping */      0.5f,
                /* hashSize */          1 << 19,
                /* enableSCorr */       true,
                /* kCorr */             0.001f,
                /* nCorr */             4.0f,
                /* deltaQ */            0.3f,
                /* cohesionStrength */  0.001f,
                /* enableViscosity */   true,
                /* viscosity */         0.1f,
                /* interactionRadius */ 2.0f,
                /* interactionStrength */ 25.0f,
                /* enableVorticity */   true,
                /* vorticityEpsilon */  0.05f,
            },
            /* camYaw */   0.6f,
            /* camPitch */ 0.5f,
            /* camDist */  20.0f,
            /* pointSize */ 5.0f,
        },

        // 4 — High-Speed Impact
        {
            "High-Speed Impact",
            {
                /* dt */                1.0f / 60.0f,
                /* gravity */           { 0.0f, -2.0f, 0.0f },
                /* h */                 0.15f,
                /* rho0 */              1200.0f,
                /* solverIterations */   6,
                /* substepIterations */  3,
                /* eps */               0.0001f,
                /* particleCount */     1 << 14,
                /* spawnMin */          { 0.3f, 0.3f, 1.5f },
                /* spawnMax */          { 2.5f, 4.0f, 4.5f },
                /* spawnRandom */       false,
                /* spacing */           0.1f,
                /* initialVelocity */   { 8.0f, 0.0f, 0.0f },
                /* boundsMin */         { 0.0f, 0.0f, 0.0f },
                /* boundsMax */         { 8.0f, 5.0f, 6.0f },
                /* boundDamping */      0.3f,
                /* hashSize */          1 << 16,
                /* enableSCorr */       true,
                /* kCorr */             0.001f,
                /* nCorr */             4.0f,
                /* deltaQ */            0.3f,
                /* cohesionStrength */  0.001f,
                /* enableViscosity */   true,
                /* viscosity */         0.1f,
                /* interactionRadius */ 1.5f,
                /* interactionStrength */ 25.0f,
                /* enableVorticity */   true,
                /* vorticityEpsilon */  0.05f,
            },
            /* camYaw */   0.0f,
            /* camPitch */ 0.4f,
            /* camDist */  11.0f,
            /* pointSize */ 7.0f,
        },

        // 5 — Viscous Goo
        {
            "Viscous Goo",
            {
                /* dt */                1.0f / 60.0f,
                /* gravity */           { 0.0f, -1.5f, 0.0f },
                /* h */                 0.15f,
                /* rho0 */              2000.0f,
                /* solverIterations */   3,
                /* substepIterations */  2,
                /* eps */               0.0001f,
                /* particleCount */     1 << 14,
                /* spawnMin */          { 1.0f, 2.0f, 1.0f },
                /* spawnMax */          { 4.0f, 5.0f, 4.0f },
                /* spawnRandom */       false,
                /* spacing */           0.1f,
                /* initialVelocity */   { 0.0f, 0.0f, 0.0f },
                /* boundsMin */         { 0.0f, 0.0f, 0.0f },
                /* boundsMax */         { 5.0f, 6.0f, 5.0f },
                /* boundDamping */      0.5f,
                /* hashSize */          1 << 15,
                /* enableSCorr */       true,
                /* kCorr */             0.001f,
                /* nCorr */             4.0f,
                /* deltaQ */            0.3f,
                /* cohesionStrength */  0.02f,
                /* enableViscosity */   true,
                /* viscosity */         0.19f,
                /* interactionRadius */ 1.5f,
                /* interactionStrength */ 25.0f,
                /* enableVorticity */   true,
                /* vorticityEpsilon */  0.05f,
            },
            /* camYaw */   0.5f,
            /* camPitch */ 0.3f,
            /* camDist */  8.5f,
            /* pointSize */ 8.0f,
        },

        // 6 — SDF Container (Leak Test): fluid spawned INSIDE a closed box mesh,
        //     held by the SDF in container mode. Watch the corners/edges for
        //     leaks. The AABB is larger than the box, so any escaped particle
        //     ends up visibly outside the wireframe. (main.cpp drops the box in
        //     when this scene is selected — center (4,4,4), half-size 2.)
        {
            "SDF Container (Leak Test)",
            {
                /* dt */                1.0f / 60.0f,
                /* gravity */           { 0.0f, -9.81f, 0.0f },
                /* h */                 0.15f,
                /* rho0 */              1000.0f,
                /* solverIterations */   4,
                /* substepIterations */  3,
                /* eps */               0.0001f,
                /* particleCount */     1 << 15,
                /* spawnMin */          { 2.4f, 3.0f, 2.4f },   // inside the box [2,6]^3, upper half
                /* spawnMax */          { 5.6f, 5.6f, 5.6f },
                /* spawnRandom */       false,
                /* spacing */           0.12f,
                /* initialVelocity */   { 0.0f, 0.0f, 0.0f },
                /* boundsMin */         { 0.0f, 0.0f, 0.0f },
                /* boundsMax */         { 8.0f, 8.0f, 8.0f },   // AABB room larger than the container
                /* boundDamping */      0.3f,
                /* hashSize */          1 << 18,
                /* enableSCorr */       true,
                /* kCorr */             0.001f,
                /* nCorr */             4.0f,
                /* deltaQ */            0.3f,
                /* cohesionStrength */  0.001f,
                /* enableViscosity */   true,
                /* viscosity */         0.1f,
                /* interactionRadius */ 1.5f,
                /* interactionStrength */ 25.0f,
                /* enableVorticity */   true,
                /* vorticityEpsilon */  0.05f,
            },
            /* camYaw */   0.6f,
            /* camPitch */ 0.35f,
            /* camDist */  16.0f,
            /* pointSize */ 6.0f,
        },
    };
    return scenes;
}

#endif
